language: node_js
node_js: 8

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --coverage
  - npm run build

after_success:
  - npm install codacy-coverage
  - $(npm bin)/codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
